Repository Team-GONG-BAEK/gong-baek-server, pull requests merged in 2025-05, with the labels that each got.

#57 [fix] #56 모임의 커버 이미지 인덱스 범위 수정
  src/main/java/com/ggang/be/api/facade/GroupRequestFacade.java
Labels: 🔨 fix 🔨

#58 클라요청 사항 배포하기 ~
  src/main/java/com/ggang/be/api/facade/GroupRequestFacade.java
Labels: release

#61 머지합니다
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
Labels: release

#63 [feat] #62 특정 유저의 테스트용 이메일 추가
  src/main/java/com/ggang/be/api/email/service/AppProperties.java
  src/main/java/com/ggang/be/api/facade/MailFacade.java
Labels: ⭐️ feat ⭐️

#69 배포 진행해요 -> app properties 빈 반영해요!
  src/main/java/com/ggang/be/api/email/service/AppProperties.java
Labels: release

#71 [feat] #70 안드로이드 테스트용 이메일 추가
  src/main/java/com/ggang/be/api/email/service/AppProperties.java
  src/main/java/com/ggang/be/api/facade/MailFacade.java
Labels: ⭐️ feat ⭐️

#72 배포합니다!
  src/main/java/com/ggang/be/api/email/service/AppProperties.java
  src/main/java/com/ggang/be/api/facade/MailFacade.java
Labels: release
